version: '3.8'

services:
  api:
    build: . # Build from Dockerfile in current directory
    ports:
      - "8000:8000" # Expose port 800to host machine
    env_file:
      - .env
    depends_on: # Ensure service starts after db
      - db
    volumes:
      - .:/app    # Mount current directory to /app in container
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    ports:
      - "3306:3306"    # Expose Port
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d  
    healthcheck: # Give DB more time to start - running into connection issues
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  mysql_data: